config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :recipes do
    collection do
      get :search
      get :favorites
      get :my
    end

    member do
      post :favorite
      delete :unfavorite, to: 'recipes#unfavorite'
      post :share
    end
  end
  resources :cuisines, only: %i[show new create edit update]
  resources :recipe_types, only: %i[show new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
  validates :name, presence: { message: 'Você deve informar o nome da cozinha' }
  validates :name, uniqueness: { message: 'Cozinha já cadastrada!' }

  def to_s
    name
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :recipe

  validates :recipe, uniqueness: { scope: :user, message: 'Receita já é favorita!' }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :cuisine
  belongs_to :recipe_type
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  has_many :favorites
  has_many :users_favored, through: :favorites, source: :user

  validates :title, :recipe_type, :cuisine,
            :difficulty, :cook_time, :ingredients, :method,
            presence:
            { message: 'Você deve informar todos os dados da receita' }

  has_attached_file :photo, styles:
                    { medium: '300x300>', thumb: '100x100>' },
                    default_url: '/images/:style/missing.png'
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  def favorited?(user)
    users_favored.include? user
  end

  def author?(user)
    return user.recipes.include? self if user
    false
  end
end

app/models/recipe_type.rb
class RecipeType < ApplicationRecord
  validates :name, presence: { message: 'Você deve informar o nome do tipo de receita' }
  validates :name, uniqueness: { message: 'Tipo da receita já cadastrada!' }

  def to_s
    name
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :recipes, inverse_of: 'author'
  has_many :favorites
  has_many :favorites_recipes, through: :favorites, source: :recipe

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :find_cuisine_aside
  before_action :find_recipe_type_aside

  private

  def find_cuisine_aside
    @cuisines = Cuisine.all
  end

  def find_recipe_type_aside
    @recipe_types = RecipeType.all
  end

  def require_login
    unless current_user == @recipe.author
      flash[:alert] = 'Acesso negado!'
      redirect_to root_path
    end
  end
end

app/controllers/cuisine_controller.rb
class CuisineController < ApplicationController

  def show
    @cuisine = Cuisine.find(params[:id])
    @recipes = Recipe.where(cuisine_id: params[:id]).all
    if @recipes.blank?
      flash[:notice] =  'Nenhuma receita encontrada para este tipo de cozinha'
    else
      flash[:notice] =  ''
    end
  end

  def new
    @cuisine = Cuisine.new
  end

  def create
    cuisine = Cuisine.new cuisine_params
    if cuisine.valid?
      cuisine.save
      redirect_to cuisine
    else
      @cuisine = cuisine
      render :new
    end
  end

  private 

  def cuisine_params
    params.require(:cuisine).permit(:name)
  end
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController
  before_action :find_cuisine, only: %i[show edit update]

  def show
    @recipes = Recipe.where(cuisine: params[:id])
    flash.now[:notice] = 'Nenhuma receita encontrada para este tipo de cozinha' if @recipes.blank?
  end

  def new
    @cuisine = Cuisine.new
  end

  def create
    @cuisine = Cuisine.new cuisine_params
    @cuisine.save ? redirect_to(@cuisine) : render(:new)
  end

  def edit; end

  def update
    @cuisine.update(cuisine_params) ? redirect_to(@cuisine) : render(edit_cuisine_path(@cuisine))
  end

  private

  def find_cuisine
    @cuisine = Cuisine.find(params[:id])
  end

  def cuisine_params
    params.require(:cuisine).permit(:name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recipes = Recipe.last(6)
    @most_favorites = []
    fav = Favorite.group(:recipe_id).limit(3).count
    fav.values.sort.reverse.each do |d|
      @most_favorites << Recipe.find(fav.key(d))
    end
  end
end

app/controllers/recipe_controller.rb
class RecipeController < ApplicationController

  def show 
    @recipe = Recipe.find(params[:id])
  end  

  def new 
    @recipe = Recipe.new
  end

  def create 
    recipe = Recipe.new(recipe_params)
    if recipe.valid?
      recipe.save
      redirect_to recipe
    else
      @recipe = recipe
      render :new
    end
  end

  private 

  def recipe_params
    params.require(:recipe).permit(:title, :recipe_type_id, :difficulty, :cuisine_id, :cook_time, :ingredients, :method)
  end
end

app/controllers/recipe_type_controller.rb
class RecipeTypeController < ApplicationController
  def show 
    @recipe_type = RecipeType.find(params[:id])
    @recipes = Recipe.where(recipe_type_id: params[:id]).all
    if @recipes.blank?
      flash[:notice] =  'Nenhuma receita encontrada para este tipo de receitas'
    else
      flash[:notice] =  ''
    end
  end

  def new
    @recipe_type = RecipeType.new
  end

  def create
    recipe_type = RecipeType.new(recipe_type_params)

    if recipe_type.valid?
      recipe_type.save
      redirect_to recipe_type
    else
      @recipe_type = recipe_type
      render :new
    end
  end
  
  private

  def recipe_type_params
    params.require(:recipe_type).permit(:name)
  end
end

app/controllers/recipe_types_controller.rb
class RecipeTypesController < ApplicationController
  before_action :find_recipe_type, only: [:show]

  def show
    @recipes = Recipe.where(recipe_type_id: params[:id])
    flash.now[:notice] = 'Nenhuma receita encontrada para este tipo de receitas' if @recipes.blank?
  end

  def new
    @recipe_type = RecipeType.new
  end

  def create
    @recipe_type = RecipeType.new(recipe_type_params)
    @recipe_type.save ? redirect_to(@recipe_type) : render(:new)
  end

  private

  def find_recipe_type
    @recipe_type = RecipeType.find(params[:id])
  end

  def recipe_type_params
    params.require(:recipe_type).permit(:name)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create my favorites]
  before_action :find_recipe, only: %i[show edit destroy update is_author favorite unfavorite share]
  before_action :require_login, only: %i[edit update destroy]

  def search
    @term = params[:term]
    @term ? @recipes = Recipe.where('title LIKE ? OR ingredients LIKE ?', "%#{@term}%", "%#{@term}%") : @recipes = Recipe.all
  end

  def index
    @recipes = Recipe.all
  end

  def show; end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.author = current_user
    @recipe.save ? redirect_to(@recipe) : render(:new)
  end

  def edit; end

  def update
    @recipe.update(recipe_params) ? redirect_to(@recipe) : render(:edit)
  end

  def destroy
    redirect_to(root_path) if @recipe.destroy
  end

  def favorite
    Favorite.create(user: current_user, recipe: @recipe)
    flash[:notice] = 'Adicionado aos favoritos com sucesso!'
    redirect_to recipe_path @recipe
  end

  def unfavorite
    Favorite.find_by(user: current_user, recipe: @recipe).destroy
    flash[:notice] = 'Removido dos favoritos com sucesso!'
    redirect_to recipe_path @recipe
  end

  def favorites
    @recipes = current_user.favorites_recipes
    flash[:notice] = 'Nenhuma receita favorita!' if @recipes.empty?
  end

  def share
    email = params[:email]
    message = params[:message]
    if RecipesMailer.share(email: email, message: message, recipe_id: @recipe.id).deliver_now
      flash[:notice] = "Receita enviada para #{email}"
    else
      flash[:alert] = "Problemas ao enviar a receita para #{email}"
    end
    redirect_to recipe_path @recipe
  end

  def my
    @recipes = Recipe.where author: current_user
    flash[:notice] = 'Você não possui receitas cadastradas!' if @recipes.empty?
  end

  private

  def find_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:photo, :title, :recipe_type_id, :difficulty, :cuisine_id, :cook_time, :ingredients, :method)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cuisine/new.html.erb
<h1>Nova Cozinha</h1>

<%= form_for @cuisine,url: cuisine_index_path(@cuisine), html: { method: :post } do |f| %>
  <% if @cuisine.errors.any? %>
    <h2> Erro: </h2>
    <ul>
    <% @cuisine.errors.messages.each do |msg| %>
      <li><%= msg.last.last %></li>
    <% end %>
    </ul>
  <% end %>

  <%= f.label :name, 'Nome' %>
  <%= f.text_field :name %>

  <%= f.submit 'Enviar' %>
<% end %>

app/views/cuisine/show.html.erb
<h1>
  <%= @cuisine.name %>
</h1>
<div class="notice"><%= flash[:notice] %></div>
<% @recipes.each do |recipe|%>
  <h1>
    <%= link_to recipe.title, recipe %>
  </h1>
  <ul>
    <li>
      <%= recipe.recipe_type %>
    </li>
    <li>
      <%= recipe.cuisine.name %>
    </li>
    <li>
      <%= recipe.difficulty %>
    </li>
    <li>
      <%= "#{recipe.cook_time} minutos" %>
    </li>
  </ul>
<%end%>

app/views/cuisines/_form.html.erb
<div class="form-group form-inline">
  <%= form_for @cuisine do |f| %>
    <% if @cuisine.errors.any? %>
      <h2> Erro: </h2>
      <ul>
      <% @cuisine.errors.messages.each do |msg| %>
        <li><div class="error"><%= msg.last.last %></div></li>
      <% end %>
      </ul>
    <% end %>

    <div class="row">
      <div class="col-md-4">
        <%= f.label :name, 'Nome' %>
        <%= f.text_field :name, class:'form-control' %>
      </div>
      <div class="col-md-1">
          <%= f.submit 'Enviar', class:'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/cuisines/edit.html.erb
<h1>Editar Cozinha</h1>

<%= render partial: "form" %>

app/views/cuisines/new.html.erb
<h1 class="page-header">Nova Cozinha</h1>

<%= render partial: "form" %>

app/views/cuisines/show.html.erb
<nav class=row>
  <section class="col-md-8">
    <h1 class="page-header"><%= @cuisine.name %></h1>
  </section>
</nav>

<article class="row">
  <h4 class="notice"><%= flash[:notice] %></h4>
  <% @recipes.each do |recipe|%>
    <%= render recipe, object: recipe %>
  <%end%>
</article>

app/views/favorites/index.html.erb
<article class="row">
  <% @recipes.each do |recipe|%>
    <section class="col-md-4">
      <h1><%= link_to recipe.title, recipe %></h1>
      <ul>
        <li>
          <%= recipe.author.email %>
        </li>
        <li>
          <%= recipe.recipe_type %>
        </li>
        <li>
          <%= recipe.cuisine %>
        </li>
        <li>
          <%= recipe.difficulty %>
        </li>
        <li>
          <%= "#{recipe.cook_time} minutos" %>
        </li>
      </ul>
    </section>
  <%end%>
</article>

app/views/home/index.html.erb
<nav class="row">
  <section class="col-md-8">
    <header class="page-header">
      <h1>CookBook</h1>
      <p>Bem-vindo ao maior livro de receitas online</p>
      <%= link_to  "Visualizar tudo", recipes_path %>
    </header>
  </section>
  <section class="col-md-4 hidden-xs">
    <h4>Receitas mais favoritadas</h4>
    <div class="most-favorite"> 
      <%= "Nenhuma receita favoritada" if @most_favorites.empty? %>
    </div>
    <% @most_favorites.each do |recipe|%>
      <ul>
        <p>
          <h4>
            <div class="most-favorite"> 
              <%= link_to recipe.title, recipe %> 
            </div>
          </h4>
        </p>
      </ul>
    <% end%>
  </section>
</nav>

<article class="row">
  <% @recipes.each do |recipe|%>
    <%= render recipe, object: recipe %>
  <%end%>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyCookbook</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <meta name="viewport" content="initial-scale=1">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    
    <section class='container'>
      <section class="row">
        <%= render 'shared/aside' %>
        <div class="col-md-9">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
          <div class="container"> 
            <%= yield %>
          </div>
        </div>
      </section>
    </section>
  </body>
</html>

app/views/recipe/new.html.erb
<h1>Nova Receita</h1>

<%= form_for @recipe,url: recipe_index_path(@recipe), html: { method: :post } do |f| %>
  <% if @recipe.errors.any? %>
    <h2> Erro: </h2>
    <ul>
    <% @recipe.errors.messages.each do |msg| %>
      <li><%= msg.last.last %></li>
    <% end %>
    </ul>
  <% end %>

  <%= f.label :title, 'Título' %>
  <%= f.text_field :title %>
  <%= f.label :cuisine_id, 'Cozinha' %>
  <%= f.select(:cuisine_id) do %>
    <% Cuisine.all.each do |c| -%>
      <%= content_tag(:option, c.name, value: c.id) %>
    <% end %>
  <% end %>
  <%= f.label :recipe_type_id, 'Tipo da Receita' %>
  <%= f.select(:recipe_type_id) do %>
    <% RecipeType.all.each do |c| -%>
      <%= content_tag(:option, c.name, value: c.id) %>
    <% end %>
  <% end %>
  <%= f.label :difficulty, 'Dificuldade' %>
  <%= f.text_field :difficulty %>
  <%= f.label :cook_time, 'Tempo de Preparo' %>
  <%= f.text_field :cook_time %>
  <%= f.label :ingredients, 'Ingredientes' %>
  <%= f.text_field :ingredients %>
  <%= f.label :method, 'Como Preparar' %>
  <%= f.text_field :method %>
  <%= f.submit 'Enviar' %>
<% end %>

app/views/recipe/show.html.erb
<h1><%= @recipe.title %></h1>
<h3>Detalhes</h3>
<p><%= @recipe.recipe_type %></p>
<p><%= @recipe.cuisine %></p>
<p><%= @recipe.difficulty %></p>
<p><%= "#{@recipe.cook_time} minutos" %></p>
<h3>Ingredientes</h3>
<p><%= @recipe.ingredients %></p>
<h3>Como Preparar</h3>
<p><%= @recipe.method %></p>

<%= link_to 'Voltar', root_path%>

app/views/recipe_type/new.html.erb
<h1>Novo Tipo de Receita</h1>

<%= form_for @recipe_type,url: recipe_type_index_path(@recipe_type), html: { method: :post } do |f| %>
  <% if @recipe_type.errors.any? %>
    <h2> Erro: </h2>
    <ul>
    <% @recipe_type.errors.messages.each do |msg| %>
      <li><%= msg.last.last %></li>
    <% end %>
    </ul>
  <% end %>

  <%= f.label :name, 'Nome' %>
  <%= f.text_field :name %>

  <%= f.submit 'Enviar' %>
<% end %>

app/views/recipe_types/new.html.erb
<h1 class="page-header">Novo Tipo de Receita</h1>

<div class="form-group form-inline">
  <%= form_for @recipe_type do |f| %>
    <% if @recipe_type.errors.any? %>
      <h2> Erro: </h2>
      <ul>
      <% @recipe_type.errors.messages.each do |msg| %>
        <li><div class="error"><%= msg.last.last %></div></li>
      <% end %>
      </ul>
    <% end %>

    <div class="row">
      <div class="col-md-42">
        <%= f.label :name, 'Nome' %>
        <%= f.text_field :name, class:'form-control' %>
      </div>
      <div class="col-md-1">
          <%= f.submit 'Enviar', class:'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/recipe_types/show.html.erb
<nav class=row>
  <section class="col-md-8">
    <h1 class="page-header"><%= @recipe_type.name %></h1>
  </section>
</nav>

<article class="row">
  <h4 class="notice"><%= flash[:notice] %></h4>
  <% @recipes.each do |recipe|%>
    <%= render recipe, object: recipe %>
  <%end%>
</article>

app/views/recipes/_form.html.erb
<section class ="row">
  <div class="form-group">
    <%= form_for @recipe do |f| %>
      <section class="row">
        <div class="col-md-6">
          <% if @recipe.errors.any? %>
            <h2> Erro: </h2>
            <ul>
            <% @recipe.errors.messages.each do |msg| %>
              <li><%= msg.last.last %></li>
            <% end %>
            </ul>
          <% end %>
        </div>
      </section>

      <section class="row ">
        <div class="col col-md-5">
          <%= f.label :photo, 'Adicionar foto' %>
          <%= f.file_field :photo %>
          <%= f.label :title, 'Título' %>
          <%= f.text_field :title, class:'form-control' %>
          <%= f.label :cuisine_id, 'Cozinha' %>
          <%= f.select(:cuisine_id) do %>
            <% Cuisine.all.each do |c| -%>
              <%= content_tag(:option, c.name, value: c.id) %>
            <% end %>
          <% end %>
          <%= f.label :recipe_type_id, 'Tipo da Receita' %>
          <%= f.select(:recipe_type_id) do %>
            <% RecipeType.all.each do |c| -%>
              <%= content_tag(:option, c.name, value: c.id) %>
            <% end %>
          <% end %>
          <%= f.label :difficulty, 'Dificuldade' %>
          <%= f.text_field :difficulty, class:'form-control' %>
          <%= f.label :cook_time, 'Tempo de Preparo' %>
          <%= f.text_field :cook_time, class:'form-control' %>
          <%= f.label :ingredients, 'Ingredientes' %>
          <%= f.text_field :ingredients, class:'form-control' %>
          <%= f.label :method, 'Como Preparar' %>
          <%= f.text_field :method, class:'form-control' %>
          <br>
          <%= f.submit 'Enviar', class:'btn btn-primary' %>
        <% end %>
    </div>
    </section>
  </div>
</section>

app/views/recipes/_recipe.html.erb
<section class="col-md-4">
  <h1>
    <%= link_to recipe.title, recipe %>
    <%if recipe.favorited? current_user %>
      <%= image_tag('star.png') unless current_page?(favorites_recipes_path)%>
    <% end %>
  </h1>
  <ul>
    <% if recipe.author %>
      <li>
        <%= recipe.author.email %>
      </li>
    <% end %>
    <li>
      <%= recipe.recipe_type %>
    </li>
    <li>
      <%= recipe.cuisine %>
    </li>
    <li>
      <%= recipe.difficulty %>
    </li>
    <li>
      <%= "#{recipe.cook_time} minutos" %>
    </li>
  </ul>
</section>

app/views/recipes/_show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title">
      <%= @recipe.title %>
      <%if @recipe.favorited? current_user %>
        <%= image_tag('star.png') %>
      <% end %>
    </h1>
  </div>
  <div class="panel-body">
    <% if @recipe.photo.file? %>
      <div class="row">
        <%= image_tag @recipe.photo.url(:medium) %>
      </div>
    <% else %>
      <p>Sem foto</p>
    <% end %>

    <h3>Detalhes</h3>
    <% if @recipe.author %>
      <p><strong>Autor: </strong> <%= @recipe.author.email %></p>
    <%end %>
    <p><strong>Tipo: </strong> <%= @recipe.recipe_type %></p>
    <p><strong>Cozinha: </strong> <%= @recipe.cuisine %></p>
    <p><strong>Dificuldade: </strong> <%= @recipe.difficulty %></p>
    <p> <strong>Tempo de preparo: </strong> <%= "#{@recipe.cook_time} minutos" %></p>
    <h3>Ingredientes: </h3>
    <p><%= @recipe.ingredients %></p>
    <h3>Como Preparar:</h3>
    <p><%= @recipe.method %></p>
  </div>
  <div class="panel-footer">
    <%= link_to 'Voltar', root_path, class:'btn btn-default'%>
    <% if current_user %>
      <% if @recipe.author? current_user %>
        <%= link_to 'Editar', edit_recipe_path(@recipe), class:'btn btn-default' %>
        <%= link_to  'Remover', recipe_path(@recipe), method: 'delete', class:'btn btn-default' %>
      <% end %>
      <% if @recipe.favorited? current_user %>
        <%= link_to  "Desfavoritar", 
          unfavorite_recipe_path, method: 'delete', class:'btn btn-default' %>
      <% else %>
        <%= link_to  'Favoritar', 
          favorite_recipe_path, method: 'post', class:'btn btn-default' %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/recipes/edit.html.erb
<h1 class="page-header" ><%= "Editar Receita #{@recipe.title }"%> </h1>

<%= render 'form' %>

app/views/recipes/favorites.html.erb
<nav class="row">
  <section class="col-md-8">
    <header class="page-header">
      <h1>CookBook</h1>
      <p>Receitas Favoritadas</p>
    </header>
  </section>
</nav>
<article class="row">
  <% @recipes.each do |recipe|%>
    <%= render recipe, object: recipe %>
  <%end%>
</article>

app/views/recipes/index.html.erb
<nav class="row">
  <section class="col-md-8">
    <header class="page-header">
      <h1>CookBook</h1>
      <p>Todas as receitas de nosso site</p>
    </header>
  </section>
</nav>

<article class="row">
  <% @recipes.each do |recipe|%>
    <%= render recipe, object: recipe %>
  <%end%>
</article>
  

app/views/recipes/my.html.erb
<nav class="row">
  <section class="col-md-8">
    <header class="page-header">
      <h1>CookBook</h1>
      <p>Todas as suas receitas</p>
    </header>
  </section>
</nav>

<article class="row">
  <% @recipes.each do |recipe|%>
    <%= render recipe, object: recipe %>
  <%end%>
</article>

app/views/recipes/new.html.erb
<h1 class="page-header" >Nova Receita</h1>

<%= render 'form' %>

app/views/recipes/search.html.erb
<nav class=row>
  <header class="col-md-8">
    <h1 class="page-header"> <%= "Resultado da busca por: #{@term}" %> </h1>
  </header>
</nav>
  
<section class="row">
  <% @recipes.each do |recipe|%>
    <%= render recipe, object: recipe %>
  <%end%>
</section>

app/views/recipes/show.html.erb
<section class="row">
  <article class="col-md-9">
    <%= render 'show'%>
  </article>
  <article class="col-md-2 col-md-offset-1">
    <div class="row">
      <h3>Enviar para um amigo</h3>
    </div>
    <div class="row">
      <%= form_tag share_recipe_path, method: :post, class: 'form-group' do  %>
        <div class="row">
          <%= label_tag :email, 'Email' %>
        </div>
        <div class="row">
            <%= text_field_tag :email,"" ,class: 'form-control' %>
          </div>
        <div class="row">
          <%= label_tag :message, 'Mensagem' %>
          <%= text_area_tag :message,"" ,class: 'form-control' %>
        </div>
        <br>
        <div class="row">
          <%= submit_tag 'Enviar', class:'btn btn-default col-md-12'  %>
        </div>
      <% end %>
    </div>
  </article>

</section>

app/views/shared/_aside.html.erb
<section class='col col-md-3 hidden-xs'>
  <aside class="left">
    <h3>Cozinha</h3>
    <% @cuisines.each do |cuisine|%>
      <ul>
        <p>
          <h4> <%= link_to cuisine.name, cuisine %> </h4>
        </p>
      </ul>
      <%end%>
      <h3>Tipos de Receita</h3>
      <% @recipe_types.each do |recipe_type|%>
        <ul>
          <p>
            <h4> <%= link_to recipe_type.name, recipe_type %> </h4>
          </p>
        </ul>
      <%end%>
  </aside>
</section>

app/views/shared/_navbar.html.erb
<header>
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
          <span class="sr-only">Toggle</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to  'CookBook', root_path,  class:"navbar-brand"  %>
      </div>
  
      <div class="collapse navbar-collapse" id="navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to  'Minhas Receitas', my_recipes_path %></li>
          <li><%= link_to  'Minhas Receitas Favoritas', favorites_recipes_path %></li>
          <li><%= link_to  'Enviar uma receita', new_recipe_path %></li>
          <li class="dropdown visible-xs">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Cozinha <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <% @cuisines.each do |cuisine|%>
                    <li><%= link_to cuisine.name.downcase, cuisine %></li>
                <%end%>
              </ul>
            </li>
            <li class="dropdown visible-xs">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Tipos de receita<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <% @recipe_types.each do |recipe_type|%>
                        <li> <%= link_to recipe_type.name.downcase, recipe_type %> </li>
                    </ul>
                  <%end%>
                </ul>
              </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li><%= link_to  'Logout', destroy_user_session_path, method: "delete" %></li>
          <% else %>
            <li><%= link_to  'Login', new_user_session_path %></li>
          <% end %>
        </ul>
        <%= form_tag(search_recipes_path, method: "get", class:'navbar-form navbar-right') do %>
          <%= label_tag(:term, "Busca", class:'label label-default') %>
          <%= text_field_tag(:term, "", class:"form-control") %>
          <%= submit_tag("Buscar", class:'btn btn-default')%>
        <% end %>
      </div>
    </div>
  </nav>
</header>